  
- name: Start Kubernetes
  hosts: azure
  user: azureuser

  tasks:  
    - name: Create Kubernetes deployment
      command: kubectl create deployment coursework2 --image=dhusar200/coursework2:latest

    - name: Create Kubernetes service
      command: kubectl expose deployment/coursework2 --type="NodePort" --port 8080 --name node-port-service

    - name: Scale deployment to 4 nodes
      command: sudo kubectl scale deployment/coursework2 --replicas=4 
